<script setup>
import { useHead } from '@vueuse/head'

useHead({
  title: 'BenefitGen Terms of Service',
  meta: [
    { name: 'description', content: 'Terms of Service for BenefitGen by HSGCraft.' }
  ]
})
</script>

<template>
  <div class="max-w-4xl mx-auto px-6 py-12 text-gray-200 bg-gray-900 rounded-lg shadow-lg overflow-y-auto max-h-[80vh]">
    <h1 class="text-3xl font-bold mb-6 text-amber-400">BenefitGen Terms of Service</h1>
    <p class="mb-6">Effective Date: 07-21-2025</p>

    <section class="mb-6">
      <h2 class="text-xl font-semibold mb-2">1. Eligibility</h2>
      <ul class="list-disc list-inside space-y-1">
        <li>You must be at least 18 years old to use BenefitGen.</li>
        <li>By using our service, you represent that you meet this age requirement and have the legal capacity to enter into this agreement.</li>
      </ul>
    </section>

    <section class="mb-6">
      <h2 class="text-xl font-semibold mb-2">2. Account Registration and Security</h2>
      <ul class="list-disc list-inside space-y-1">
        <li>You must create an account to access certain features.</li>
        <li>You agree to provide accurate and complete registration information.</li>
        <li>You are responsible for maintaining the confidentiality of your account credentials and for all activities under your account.</li>
      </ul>
    </section>

    <section class="mb-6">
      <h2 class="text-xl font-semibold mb-2">3. Service Description</h2>
      <ul class="list-disc list-inside space-y-1">
        <li>BenefitGen helps transform technical documentation into business-aligned summaries.</li>
        <li>Currently, input is provided <strong>via a text box</strong> where you can copy/paste or type your technical documentation.</li>
        <li>Support for uploading <code>.txt</code>, <code>.md</code>, readme files, or changelogs is planned for future releases.</li>
        <li>The service is provided on an <strong>“AS IS”</strong> basis without warranties of any kind.</li>
      </ul>
    </section>

    <section class="mb-6">
      <h2 class="text-xl font-semibold mb-2">4. User Content and Conduct</h2>
      <ul class="list-disc list-inside space-y-1">
        <li>You retain ownership of your input content.</li>
        <li>You agree <strong>not to submit any personally identifiable information (PII) or sensitive data</strong> through BenefitGen.</li>
        <li>We implement automated checks to detect and block PII. Accounts violating PII policies may be suspended or banned.</li>
        <li>You are responsible for ensuring your inputs comply with applicable laws and these Terms.</li>
      </ul>
    </section>

    <section class="mb-6">
      <h2 class="text-xl font-semibold mb-2">5. Usage Limits and Subscription</h2>
      <ul class="list-disc list-inside space-y-1">
        <li>Free plan users receive 40 cards/month; Pro plan users receive 450 cards/month with enhanced features.</li>
        <li>No refunds are provided for subscription fees.</li>
        <li>Subscriptions are billed monthly and may not be canceled mid-period. You will be charged for the full month.</li>
        <li>You may downgrade or upgrade your subscription anytime via your account settings.</li>
      </ul>
    </section>

    <section class="mb-6">
      <h2 class="text-xl font-semibold mb-2">6. Output Disclaimer and Audit Requirement</h2>
      <ul class="list-disc list-inside space-y-1">
        <li>All outputs generated by BenefitGen are AI-assisted and for informational purposes only.</li>
        <li>You <strong>must audit and verify</strong> all generated content before use.</li>
        <li>BenefitGen and HSGCraft disclaim all liability for any loss, damage, or negative outcomes arising from reliance on generated outputs.</li>
      </ul>
    </section>

    <section id="section-7" class="my-8">
        <h2 class="text-xl font-semibold mb-2">7. Community Plan (Upcoming)</h2>
        <p class="text-gray-300">
        We plan to launch a Community Plan available only to users in the United States, excluding California.
        This plan may collect anonymized input/output (I/O) pairs and user feedback to improve BenefitGen’s performance.
        Use of the Community Plan will require consent to this data collection.
        Participation is optional and subject to separate terms at launch.
        </p>
    </section>

    <section class="mb-6">
      <h2 class="text-xl font-semibold mb-2">8. Intellectual Property</h2>
      <ul class="list-disc list-inside space-y-1">
        <li>All software, code, trademarks, and content provided by BenefitGen remain the exclusive property of HSGCraft or its licensors.</li>
        <li>You may not copy, distribute, modify, or create derivative works without prior written consent.</li>
      </ul>
    </section>

    <section class="mb-6">
      <h2 class="text-xl font-semibold mb-2">9. Termination and Suspension</h2>
      <ul class="list-disc list-inside space-y-1">
        <li>We reserve the right to suspend or terminate accounts violating these Terms, including PII violations or abusive behavior.</li>
        <li>Upon termination, your access to the service will cease immediately.</li>
      </ul>
    </section>

    <section class="mb-6">
      <h2 class="text-xl font-semibold mb-2">10. Limitation of Liability</h2>
      <ul class="list-disc list-inside space-y-1">
        <li>To the fullest extent permitted by law, BenefitGen and HSGCraft are not liable for any indirect, incidental, consequential, or punitive damages arising from your use of the service.</li>
      </ul>
    </section>

    <section class="mb-6">
      <h2 class="text-xl font-semibold mb-2">11. Governing Law</h2>
      <p>These Terms are governed by and construed in accordance with the laws of the State of New Jersey, USA.</p>
    </section>

    <section class="mb-6">
      <h2 class="text-xl font-semibold mb-2">12. Changes to Terms</h2>
      <p>We may update these Terms occasionally. We will notify you of significant changes via email or on our website. Continued use after changes constitutes acceptance of the new Terms.</p>
    </section>

    <section>
      <h2 class="text-xl font-semibold mb-2">13. Contact Us</h2>
      <p>For support or questions regarding these Terms, please contact: <a href="mailto:support@hsgcraft.com" class="text-amber-400 underline">support@hsgcraft.com</a></p>
    </section>
  </div>
</template>

<style scoped>
/* Optional: scrollbar styling for better UX */
::-webkit-scrollbar {
  width: 8px;
}
::-webkit-scrollbar-thumb {
  background-color: #f59e0b; /* amber-400 */
  border-radius: 4px;
}
</style>
